import { ClerkProvider } from "@clerk/nextjs";
import "~/styles/globals.css";
import { dark, neobrutalism } from "@clerk/themes";

import { Manrope } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import { Metadata } from "next";
import Navbar from "./_components/navbar/Navbar";

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: {
    template: "%s | Audiophile",
    default: "Home | Audiophile",
  },
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
      }}
    >
      <html lang="en">
        <body className={`font-sans ${manrope.variable}`}>
          <TRPCReactProvider>
            <Navbar />
            {children}
          </TRPCReactProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
